{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-app.fullname" . }}-nginx
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
data:
  default.conf: |
{{ .Values.nginx.config | indent 4 }}
{{- end }}
